name: SAST

on: [push]

jobs:
  pmd:
    name: PMD SAST
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install PMD
      run: |
        curl -O https://github.com/pmd/pmd/releases/download/pmd_releases%2F7.0.0-rc3/pmd-dist-7.0.0-rc3-bin.zip
        unzip pmd-dist-7.0.0-rc3-bin.zip


    - name: Run PMD
      run: ./pmd-bin-7.0.0-rc3/bin/run.sh pmd -d . -R rulesets/java/security.xml -f textcolor




