name: SAST

on: [push]

jobs:
  pmd:
    name: PMD SAST
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Java
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    - name: Install PMD
      run: |
        curl -O https://pmd.github.io/pmd-6.38.0/pmd-bin-6.38.0.zip
        unzip pmd-bin-6.38.0.zip

    - name: Run PMD
      run: ./pmd-bin-6.38.0/bin/run.sh pmd -d . -R rulesets/java/security.xml -f textcolor

