name: Java CI with Gradle

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:
    uses: mehmetmgrsl/maven-cicd-demo/.github/workflows/maven-build.yml@main
    with:
      java-version: '11'
  semver:
    needs: build
    uses: mehmetmgrsl/maven-cicd-demo/.github/workflows/semver.yml@main
    with:
      sem_ver_increment: ${{ vars.SEM_VER_INCREMENT }}
    secrets:
      docker_pat: ${{ secrets.DOCKER_PAT }} 

  publish:
    needs: [build, semver]
    uses: mehmetmgrsl/maven-cicd-demo/.github/workflows/publish.yml@main
    with:
      version: ${{ needs.semver.outputs.version }}
      artifact-name: my-artifact
      artifact-path: project.jar
    secrets:
      docker_pat: ${{ secrets.DOCKER_PAT }}