name: Java CI with Gradle

on:
  push:
    branches: [ "feature/common-ci-cd" ]

permissions:
  contents: read

jobs:
  build:
    uses: mehmetmgrsl/maven-cicd-demo/.github/workflows/maven-build.yml@feature/common-ci-cd
    with:
      java-version: '11'
  semver:
    needs: build
    uses: mehmetmgrsl/maven-cicd-demo/.github/workflows/semver.yml@feature/common-ci-cd
    with:
      sem_ver_increment: ${{ vars.SEM_VER_INCREMENT }}
    secrets:
      docker_pat: ${{ secrets.DOCKER_PAT }} 

  publish:

    needs: [build, semver]
    runs-on: ubuntu-latest   
    
    steps:
    - uses: actions/checkout@v3

    - uses: actions/download-artifact@v3
      with:
        name: my-artifact
        path: project.jar

    - name: Login to GitHub Container Registry
      id: login_github_registry

      uses: docker/login-action@v2
      with:
         registry: ghcr.io
         username: ${{ github.actor }}
         password: ${{ secrets.DOCKER_PAT }}

    - name: Build and push Docker image
      id: increment_version

      run: |
        echo "$GITHUB_OUTPUT $GITHUB_OUTPUT"
        version=${{needs.semver.semver.outputs.new-version}}
        docker build -t ghcr.io/${{ github.repository }}:$version . 
        docker push ghcr.io/${{ github.repository }}:$version
