name: SAST

on: [push]

jobs:
  pmd:
    name: PMD SAST
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: maven

    - name: Install PMD
      run: |
        curl -O https://pmd.github.io/pmd-6.38.0/pmd-bin-6.38.0.zip
        unzip pmd-bin-6.38.0.zip

    - name: Run PMD
      run: ./pmd-bin-6.38.0/bin/run.sh pmd -d . -R rulesets/java/security.xml -f textcolor

