name: SAST

on: [push]

jobs:
  pmd:
    name: PMD SAST
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '11'
    - uses: pmd/pmd-github-action@v1
      with:
        rulesets: 'ruleset.xml'



