name: CI/CD with Maven/Docker

on:
  push:
    branches: [ "self-hosted-runner" ]

permissions:
  contents: read
jobs:
  build:
    uses: mehmetmgrsl/github-common-workflows/.github/workflows/maven-build.yml@self-hosted-runner
    with:
      java-version: '11'
      artifact-name: my-artifact
      artifact-path: my-artifact-path
  semver:
    needs: build
    uses: mehmetmgrsl/github-common-workflows/.github/workflows/semver.yml@self-hosted-runner
    with:
      sem_ver_increment: ${{ vars.SEM_VER_INCREMENT }}
    secrets:
      docker_pat: ${{ secrets.DOCKER_PAT }} 

  publish:
    needs: [build, semver]
    uses: mehmetmgrsl/github-common-workflows/.github/workflows/publish.yml@self-hosted-runner
    with:
      version: ${{ needs.semver.outputs.version }}
      artifact-name: my-artifact
      artifact-path: my-artifact-path
    secrets:
      docker_pat: ${{ secrets.DOCKER_PAT }}